###
# @name invoiceProcessingRequests 
POST http://127.0.0.1:8080/invoice-processing-requests
Content-Type: multipart/form-data; boundary=jj

--jj
Content-Disposition: form-data; name="invoice"; filename="invoice.pdf"
Content-Type: application/pdf

< ./invoices/invoice_3.pdf

--jj--